version: '3'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.40.5}
    container_name: prometheus
    network_mode: "host"
    expose:
      - 9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-9.2.3}
    container_name: grafana
    network_mode: "host"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    ports:
      - 3000:3000

volumes:
  prometheus_data: {}
  grafana_data: {}

