- name: Configure plan rating options
  become: yes
  hosts: all
  vars:
    node_exporter_version: "{{ node_exporter_ver | default('1.1.2') }}"
    prometheus_version: "{{ prometheus_ver | default('v2.40.5') }}"
    grafana_version: "{{ grafana_ver | default('9.2.3') }}"
    grafana_user: "{{ grafana_admin | default('admin') }}"
    grafana_password: "{{ grafana_passwd | default('admin') }}"

  tasks:
    - name: Install required packages
      apt:
        update_cache: yes
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker and docker-compose
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Start docker service
      service:
        name: docker
        enabled: yes
        state: started

    - name: Download node exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

    - name: Unpack node exporter
      unarchive:
        remote_src: yes
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp

    - name: Copy node exporter to /usr/local/bin
      copy:
        src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: yes
        mode: 0755

    - name: Copy node exporter init file to systemd
      copy:
        src: templates/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        mode: 0600

    - name: Enable node_exporter service
      systemd:
        daemon_reload: yes
        enabled: yes
        state: started
        name: node_exporter.service

    - name: Deploy prometheus and grafana docker comtainers
      shell:
        cmd: docker compose up -d
        chdir: /vagrant/provisioning
      environment:
        PROMETHEUS_VERSION: "{{ prometheus_version }}"
        GRAFANA_VERSION: "{{ grafana_version }}"
        ADMIN_PASSWORD: "{{ grafana_password }}"
        ADMIN_USER: "{{ grafana_user }}"

    - name: Allow vagrant user to manage docker
      shell:
        cmd: usermod -aG docker vagrant
